name: microproject-video-frame-scene-recognition-model Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-video-frame-scene-recognition-model/requirements.txt
    - run: pip install -r microproject-video-frame-scene-recognition-model/requirements.txt
    - name: Checkout release
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/microprojects-autograder-capeable
        ref: microproject-video-frame-scene-recognition-model
        path: release
    - name: Fetch Jupyter Notebook Autograder Script 
      uses: actions/checkout@v3
      with:
        repository: dsdiscovery/jupyter-notebook-autograder
        path: autograder
    - run: python3 -m pip install -r autograder/requirements.txt
    - run: >
        python3 autograder/generate_compiled_testcases.py
        microproject-video-frame-scene-recognition-model/microproject-video-frame-scene-recognition-model.ipynb
        release/microproject-video-frame-scene-recognition-model/microproject-video-frame-scene-recognition-model.ipynb
        microproject-video-frame-scene-recognition-model/test_microproject-video-frame-scene-recognition-model.py
    - run: python3 -m pip install pytest
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: microproject-video-frame-scene-recognition-model/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
    - run: rm microproject-video-frame-scene-recognition-model/test_microproject-video-frame-scene-recognition-model.py
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
