name: microproject-bechdel-test Grading
'on':
  workflow_dispatch: {}
jobs:
  autograding:
    name: autograding
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - name: Checkout
      id: sr-checkout
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        cache-dependency-path: microproject-bechdel-test/requirements.txt
    - run: pip install -r microproject-bechdel-test/requirements.txt
    - name: Checkout release repository
      id: release-checkout
      uses: actions/checkout@v2
      with:
        repository: dsdiscovery/microprojects
        ref: microproject-bechdel-test
        path: release
    - name: Install Extractor
      run: pip install jupyter2pytest
    - name: Generate Test Script
      run: 'python3 -m jupyter2pytest microproject-bechdel-test/microproject-bechdel-test.ipynb "### ASSIGNMENT CODE for Puzzle (.*) ==" release/microproject-bechdel-test/microproject-bechdel-test.ipynb "### TEST CASE for Puzzle (.*) ==" test_microproject-bechdel-test.py '
    - name: Download cell-replace
      uses: actions/checkout@v3
      with:
        repo: dsdiscovery/cell-replace
        path: microproject-bechdel-test/cell-replace
    - name: Autograding
      id: autograding
      uses: illinois/autograding@v3
      with:
        path: microproject-bechdel-test/
        test_suite: autograding
        step_summary: true
        all_or_nothing: true
    - name: Generate workflow summary
      if: ${{ always() }}
      run: echo -e "$(sh ./.github/workflows/gen-status-report.sh)" >> $GITHUB_STEP_SUMMARY
      env:
        sr_checkout_status: ${{ steps.sr-checkout.outcome }}
        autograding_status: ${{ steps.autograding.outcome }}
        points: ${{ steps.autograding.outputs.Points }}
